### ISSUE TITLE
bot not starting

### ISSUE THREAD

**Issue by mrblacktz** [Mirasaki/cftools-discord-bot#89]
im fairly new to this all, having issues with my bot starting up, 

[14:39:40] [DEBUG]  : [ END ] Global Command Data
[14:39:40] [DEBUG]  : [ END ] Refreshing Application (/) Commands.
[14:39:40] [SUCCESS]: Finished initializing after 986.75 ms
C:\Users\patri\Desktop\bot\cftools-discord-bot-main\node_modules\@discordjs\ws\dist\index.js:1066
        throw new Error("Used disallowed intents");
              ^

Error: Used disallowed intents
    at WebSocketShard.onClose (C:\Users\patri\Desktop\bot\cftools-discord-bot-main\node_modules\@discordjs\ws\dist\index.js:1066:15)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (C:\Users\patri\Desktop\bot\cftools-discord-bot-main\node_modules\ws\lib\websocket.js:258:10)    at TLSSocket.socketOnClose (C:\Users\patri\Desktop\bot\cftools-discord-bot-main\node_modules\ws\lib\websocket.js:1264:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)

Node.js v18.16.0

**Comment by tobiasreichel** [comment]
go to your  discord bot page and set the message intent

**Comment by tobiasreichel** [comment]
DISCORD_TO_DAYZ_LIVE_CHAT_RELAY: This module requires the privileged Discord "Message Content Intent" (Your App > Bot > Enable Message Content Intent). This module also required the following permissions in the channel where Discord messages are relayed from: View Channel and Read Message History

**Comment by mrblacktz** [comment]
do i have to re add the bot to the server once this has been done?
because it starts and all works now, but id like to set it that players may only use the leaderboard function and nothing else,

**Comment by Mirasaki** [comment]
Awesome, thanks for taking care of this tobias 💪
